# Generated by Django 3.2.4 on 2023-04-10 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=50)),
                ('engine', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('mileage', models.DecimalField(decimal_places=0, max_digits=6)),
                ('location', models.CharField(max_length=50)),
                ('condition', models.CharField(choices=[('used', 'used'), ('new', 'new')], max_length=50)),
                ('day_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cars.car')),
            ],
        ),
    ]
